"""
metta_bridge.py — pettaSH subprocess adapter for the MeTTa AtomSpace.
═══════════════════════════════════════════════════════════════════════
Uses petta (via `petta sh <script.metta>`) as the MeTTa interpreter.
Python communicates with petta through temp files + stdout capture.

Why subprocess instead of `from hyperon import MeTTa`:
  - User runs petta as their MeTTa interpreter (pettaSH)
  - No Python package needed: `petta sh` handles everything
  - Fresh process per query = no stale AtomSpace state
  - market_state.metta is re-read from disk each time → always live

This file does ONLY 3 things:
  1. Build a composite .metta script per query (imports + expression)
  2. Spawn `petta sh <script>`, capture stdout
  3. Parse S-expression output → Python dict (regex, no logic)
"""

import re
import subprocess
import tempfile
import os
from pathlib import Path
from typing import Any


# ── S-expression parsing helpers ──────────────────────────────
_QUOTED_RE = re.compile(r'"([^"]*)"')


class MeTTaBridge:
    """
    pettaSH-based MeTTa runner.

    Args:
        metta_dir: directory containing the .metta files
        petta_cmd: shell command for petta (default: "petta")
                   Override if petta is not on PATH:
                   MeTTaBridge(petta_cmd="/usr/local/bin/petta")
    """

    def __init__(self, metta_dir: str = "metta", petta_cmd: str = "petta"):
        self.metta_dir = Path(metta_dir).resolve()
        self.petta_cmd = petta_cmd
        self._kb = self.metta_dir / "knowledge_base.metta"
        self._ms = self.metta_dir / "market_state.metta"
        self._rh = self.metta_dir / "risk_hierarchy.metta"
        self._ml = self.metta_dir / "main_logic.metta"

    # ─────────────────────────────────────────────────────────
    # PUBLIC API — used by LangChain pipeline
    # ─────────────────────────────────────────────────────────

    def verify_trade(self, action: str, asset: str, size_pct: float) -> dict[str, Any]:
        """Ask MeTTa: is this trade allowed? Returns verdict dict."""
        raw = self._run("!(check-trade {action} {asset} {pct})".format(
            action=action, asset=asset, pct=size_pct))
        return self._parse_verdict(raw, asset, action) if raw else {
            "verdict": "Error", "reason": "pettaSH returned no output.",
            "asset": asset, "action": action, "raw": ""}

    def asset_info(self, asset: str) -> dict[str, Any]:
        raw = self._run(f"!(asset-info {asset})")
        return self._parse_asset_info(raw) if raw else {"error": f"Unknown asset: {asset}"}

    def market_summary(self) -> dict[str, Any]:
        raw = self._run("!(market-summary)")
        return self._parse_market_summary(raw) if raw else {
            "state": "Unknown", "balance": "?", "daily_pnl": "?", "trades_this_hour": "?"}

    def portfolio_risk(self) -> list[dict]:
        lines = self._run_multi("!(portfolio-risk)")
        return [self._parse_asset_risk(ln) for ln in lines if ln.strip()]

    def update_market_state(self, atoms: list[str]) -> None:
        """
        Overwrite market_state.metta with fresh atoms from the feeder.
        pettaSH re-reads from disk on each query, so this is always live.
        """
        header = "; AUTO-GENERATED by market_feeder.py — do not edit\n\n"
        self._ms.write_text(header + "\n".join(atoms) + "\n")

    def ping(self) -> tuple[bool, str]:
        """Check pettaSH availability and .metta file presence."""
        try:
            r = subprocess.run(
                [self.petta_cmd, "--version"],
                capture_output=True, text=True, timeout=5)
            files_ok = all(p.exists() for p in [self._kb, self._ms, self._rh])
            msg = f"petta OK (exit {r.returncode}), files {'OK' if files_ok else 'MISSING'}"
            return r.returncode == 0 and files_ok, msg
        except FileNotFoundError:
            return False, f"'{self.petta_cmd}' not found in PATH"
        except Exception as e:
            return False, str(e)

    # ─────────────────────────────────────────────────────────
    # SUBPROCESS CORE
    # ─────────────────────────────────────────────────────────

    def _build_script(self, query: str) -> str:
        """
        Build a self-contained .metta script:
          1. Import knowledge base (static rules, never changes)
          2. Import market state (live data, rewritten each poll)
          3. Import risk hierarchy (logic engine)
          4. Import main logic (API functions)
          5. Execute the query expression
        pettaSH evaluates top-to-bottom, so imports define context.
        """
        return (
            f'; pettaSH auto-generated runner script\n'
            f'!(import! &self "{self._kb}")\n'
            f'!(import! &self "{self._ms}")\n'
            f'!(import! &self "{self._rh}")\n'
            f'!(import! &self "{self._ml}")\n'
            f'{query}\n'
        )

    def _run(self, query: str) -> str:
        """Run one MeTTa query, return first result line."""
        lines = self._run_multi(query)
        return lines[0] if lines else ""

    def _run_multi(self, query: str) -> list[str]:
        """Run a MeTTa query, return all result lines (for multi-atom results)."""
        script = self._build_script(query)
        tmp_path = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".metta", delete=False, prefix="aco_"
            ) as f:
                f.write(script)
                tmp_path = f.name

            result = subprocess.run(
                [self.petta_cmd, "sh", tmp_path],
                capture_output=True, text=True, timeout=30
            )
            # pettaSH may use stdout or stderr depending on version
            output = result.stdout.strip() or result.stderr.strip()
            return self._filter_output(output)

        except FileNotFoundError:
            raise RuntimeError(
                f"\n[MeTTaBridge] ERROR: '{self.petta_cmd}' not found.\n"
                "Install petta: https://github.com/trueagi-io/metta-wam\n"
                "Then run: petta sh <file.metta>\n"
            )
        except subprocess.TimeoutExpired:
            return [f"(Error pettaSH-timeout)"]
        finally:
            if tmp_path and os.path.exists(tmp_path):
                os.unlink(tmp_path)

    def _filter_output(self, raw: str) -> list[str]:
        """Keep only lines that look like MeTTa atom results."""
        good = []
        for line in raw.splitlines():
            line = line.strip()
            if not line:
                continue
            # Specifically look for TradeApproved, TradeDenied, TradeWarned, AssetInfo, MarketSummary, AssetRisk
            if any(pattern in line for pattern in ["TradeApproved", "TradeDenied", "TradeWarned", "AssetInfo", "MarketSummary", "AssetRisk"]):
                good.append(line)
        return good

    # ─────────────────────────────────────────────────────────
    # S-EXPRESSION PARSERS  (format only, zero logic)
    # ─────────────────────────────────────────────────────────

    def _parse_verdict(self, atom_str: str, asset: str, action: str) -> dict:
        """Parse pettaSH verdict atom → Python dict."""
        inner = atom_str.strip()
        if inner.startswith("(") and inner.endswith(")"):
            inner = inner[1:-1]

        reason_m = _QUOTED_RE.search(inner)
        reason   = reason_m.group(1) if reason_m else ""
        clean    = _QUOTED_RE.sub("", inner)
        tokens   = clean.split()

        verdict_type = tokens[0] if tokens else "Unknown"
        v_asset  = tokens[1] if len(tokens) > 1 else asset
        v_action = tokens[2] if len(tokens) > 2 else action

        if not reason and len(tokens) > 3:
            reason = " ".join(tokens[3:])

        verdict_map = {
            "TradeApproved": "Allow",
            "TradeDenied":   "Deny",
            "TradeWarned":   "Warn",
        }
        return {
            "verdict": verdict_map.get(verdict_type, verdict_type),
            "asset":   v_asset,
            "action":  v_action,
            "reason":  reason.strip(),
            "raw":     atom_str,
        }

    def _parse_asset_info(self, atom_str: str) -> dict:
        tokens = atom_str.strip("()").split()
        keys = ["_type","asset","class","risk","max_pct","price","volatility","sentiment","trend"]
        d = dict(zip(keys, tokens))
        d.pop("_type", None)
        return d

    def _parse_market_summary(self, atom_str: str) -> dict:
        tokens = atom_str.strip("()").split()
        keys = ["_type","state","balance","daily_pnl","trades_this_hour"]
        d = dict(zip(keys, tokens))
        d.pop("_type", None)
        return d

    def _parse_asset_risk(self, atom_str: str) -> dict:
        tokens = atom_str.strip("()").split()
        keys = ["_type","asset","class","risk_level"]
        d = dict(zip(keys, tokens))
        d.pop("_type", None)
        return d
